### ISSUE TITLE
[iOS] PurchaseToken is null for SandBox

### ISSUE THREAD

**Issue by AndreiMisiukevich** [jamesmontemagno/InAppBillingPlugin#115]
Hi, i want to validate purchase on our server, so we need to retrieve PurchaseToken, don't we?

## Bug Information

Version Number of Plugin: 1.2.4
Device Tested On: Iphone 7
Version of VS: Vs for mac 7.3.3 (build 12)
Version of Xamarin: Xamarin.Forms 2.5.0.122203

### Steps to reproduce the Behavior
Try to purchase any item

### Expected Behavior
There is purchase token

### Actual Behavior
There are no token

### Code snippet
` if (!(await Billing.ConnectAsync()))
                {
                    return new PurchaseResponse { ErrorMessage = "error" };
                }
                var productType = request.ProductType;
                var productId = GetProductId(productType);
                var purchaseType = GetPurchaseType(productType);

                var purchase = await Billing.PurchaseAsync(productId, purchaseType, UserAgent);

                //here is purchase.PurchaseToken == null
            }
            catch (Exception ex) //purchase is null or something else
            {
                Debug.WriteLine(ex);
                return new PurchaseResponse
                {
                    ErrorMessage = "Error"
                };
            }
            finally
            {
                await Billing.DisconnectAsync();
            }`

### Screenshotst
<img width="660" alt="p" src="https://user-images.githubusercontent.com/10124814/35808010-898cbe10-0a95-11e8-980d-8d7e86d6177a.png">

**Comment by AndreiMisiukevich** [comment]
Maybe, it would be better to pass receipt in this field?

**Comment by jamesmontemagno** [comment]
You need to implement IInAppBillingVerifyPurchase : https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html

**Comment by arvybugtong** [comment]
Bug Information
Version Number of Plugin: 1.2.4.130.beta Device Tested On: iPod touch 6th gen Version of VS: Vs for mac 7.1.5 (build 2) Version of Xamarin: Xamarin.Forms 2.5.0.121934
Steps to reproduce the Behavior
Try to purchase any item
Implemented InAppBillingVerifyPurchase and it returned signedData,productId, and transactionId
Expected Behavior
There is purchase token and payload
Actual Behavior
There are no purchase token and payload

**Comment by AndreiMisiukevich** [comment]
@arvybugtong 
Guys, we fixed this issue long ago.

In our case, we had to fill all legal information

https://developer.apple.com/library/content/technotes/tn2259/_index.html

**Comment by arvybugtong** [comment]
@AndreiMisiukevich So that's why. Thank you for the information. I just found out that tax info is not yet approved.

**Comment by arvybugtong** [comment]
@AndreiMisiukevich Unfortunately the issue still persists even though I had filled all the legal information.

**Comment by stephenmante** [comment]
@jamesmontemagno @AndreiMisiukevich 
Also facing this issue in Auto Renewable Subscription, All legal information were filled and also implemented the IInAppBillingVerifyPurchase. I just want to ask of where I can get the purchase token and payload since it is not included in the purchase return that can be found in this link https://github.com/jamesmontemagno/InAppBillingPlugin/blob/52833c0fd185b9124fe77d6ec6f1e2df62cc24f0/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L191

**Comment by marcoeig** [comment]
@jamesmontemagno any update on this issue? facing the same issue, don't know how to proceed

**Comment by stefanodonofrio** [comment]
I'm facing the same problem on Sandbox environment. Any Update?
