### ISSUE TITLE
PurchaseAsync no longer has payload

### ISSUE THREAD

**Issue by qgroup-westacotta** [jamesmontemagno/InAppBillingPlugin#313]
So using V4 of the plug-in. 

I noticed that PurchaseAsync no longer has the developer payload parameter. 

How do I now communicate app specific data so I validate this on the backend?

Thanks

**Comment by jamesmontemagno** [comment]
Correct, payload was just a check and google removed it from the API. You can still get the payload when you implement IValidate as usual.

**Comment by qgroup-westacotta** [comment]
ok.

So i’ve implemented the google pub/sub updates for subscription updates in my server.  It give out the developer payload stuff but only if i use v2 of the plugin.  Just wondering how i can get that to the backend and continue to use the pub/sub updates?

On 27 Sep 2020, at 16:31, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:



Correct, payload was just a check and google removed it from the API. You can still get the payload when you implement IValidate as usual.

**Comment by jamesmontemagno** [comment]
Yeah there is still the same payload you get back for data and signature -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/feature/new-android-billing/src/Plugin.InAppBilling/InAppBilling.android.cs#L268

They "payload" was a parameter that was sent in that the library used to verify, but google doesn't use that. but your server should still get the info you need from the library.

**Comment by qgroup-westacotta** [comment]
I’m 100% misunderstanding something.

the “payload” parameter that was pass in to the older version of PurchaseAsync was actually used by google and gets pass around on the server side notifications from google.  I used this to tie an IAP notification back to the user record i keep in my app.

I’m not really clear how i do that now?  Are any of the other fields in i get back from google stable enough to use to link to a user record from the tap server side notification?


[X]             Andrew Westacott
Chief Technology Officer
Q Group Technology Ltd
________________________________
P: 07712 279 564
A: 92 Station Road, Clacton-on-sea, Essex, CO15 1SG
W: www.qgroup.tech<http://www.qgroup.tech>



On 27 Sep 2020, at 16:53, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:



Yeah there is still the same payload you get back for data and signature -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/feature/new-android-billing/src/Plugin.InAppBilling/InAppBilling.android.cs#L268

They "payload" was a parameter that was sent in that the library used to verify, but google doesn't use that. but your server should still get the info you need from the library.

**Comment by jamesmontemagno** [comment]
Developer Payload was removed by Google -> https://developer.android.com/google/play/billing/developer-payload

You would want to take a look at -> https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html

When I call "VerifyPurchase" you will get the following:
signedData: Purchase Data returned from Google
signature: Data Signature returned from Google

I would look at the Google docs as well -> https://developer.android.com/google/play/billing/security

**Comment by NullQubit** [comment]
Developer payload was removed, but they added 'Purchase attribution' for purposes of identifying which account made the purchase (e.g. from pub/sub).  How will we pass this attributes to PurchaseAsync so that the library passes them to google API?
